import Head from 'next/head'
import Image from 'next/image'

import Hero from '../components/Hero'
import Nav from '../components/Nav'
import Section from '../components/Section'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Nav></Nav>
        <Hero></Hero>
        <Section></Section>


      </main>

    </div>
  )
}
